name: food_recognizer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  envied: ^1.3.1
  
  firebase_core: ^4.2.0
  firebase_ml_model_downloader: ^0.4.0+3
  flutter:
    sdk: flutter
  gif_view: ^1.0.3
  google_generative_ai: ^0.4.7
  http: ^1.5.0
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  mime: ^2.0.0
  provider: ^6.1.5+1
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  envied_generator: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/gif/
